Glossary = {
    "Ally" : "A Unit on your side of the Board",
    "Ambush" : "Play face down and only reveal when certain conditions are met",
    "Armor" : "Absorbs a given amount of Damage dealt to a Unit",
    "Banish" : "Remove the card from the game",
    "Bond" : "Trigger this ability each time another copy of this Unit is played on the same side",
    "Boon" : "Positive row effects, can be removed by some cards and replaced by other Boons and Hazards",
    "Boost" : "Increase a Unit’s current Power",
    "Brave" : "Trigger this ability if your opponent is winning the current round",
    "Charm" : "Move an enemy to your side",
    "Clash" : "Trigger this ability only if neither player has passed",
    "Conceal" : "Turn a revealed card over",
    "Consume" : "Destroy a unit by eating it",
    "Counter" : "Reduce the counter whenever the given condition is met. When it reaches 0, trigger the Activation ability. Reset the Counter when the Unit leaves the Board",
    "Create" : "Select a card form a choice of three faction or neutral cards and Spawn it",
    "Crewmen X" : "When a Unit with a Fresh Crewmen ability is played adjacent to this Unit, trigger that ability X times",
    "Damage" : "Decreese a Unit’s current power",
    "Damaged" : "A Damaged Unit’s current Power is less than its base Power",
    "Deathwish" : "Trigger thgis ability when the card is moved to the Graveyard",
    "Demote" : "Convert the card to silver (or Bronze, if Bronze was the card’s original color)",
    "Deploy" : "Trigger this ability when the card is played on the field",
    "Destroy" : "Move the card to the Graveyard",
    "Discard" : "Move the card to the Graveyard from the Hand or Deck",
    "Doomed" : "Units: Banish when Destroyed (not when Discarded); Special Cards: Banish after triggering the card’s ability",
    "Draw" : "Move the top card of cards from your Deck to your Hand",
    "Drain" : "Steal Power from a unit",
    "Duel" : "Units deal their Power’s damage to one another until one of them is destroyed",
    "Effort" : "Perform the specified action for every card targeted by the preceding ability",
    "Enemy" : "A Unit on your opponent’s side of the field",
    "Fresh Crew" : "Trigger this ability when this Unit is played adjacent to a Unit with a Crewmen ability",
    "Gamble" : "Play a game of chance",
    "Hazard" : "Negative row effect. Can be removed by some cards and replaced by other Hazards and Boons",
    "Heal" : "Restore a Damaged Unit to its base Power",
    "Highest" : "Highest Power. Ties are resolved randomly",
    "Immune" : "Doesn’t allow both players to target the card that has this ability",
    "Lock" : "Disable a card’s abilities. Disables and reveals Ambushes",
    "Lowest" : "Lowest Power. Ties are resolved randomly",
    "Mulligan" : "Exchange a certain number of cards in your Hand for cards from your Deck including Golds (unless stated otherwise)",
    "Orders" : "Triggers this ability when your Leader card is played (but before the Leader’s ability is resolved)",
    "Promote" : "Convert the card to Gold until the round ends",
    "Regressing" : "When this Unit is removed from the board, its base Power is returned to the value it has in the collection. Not disabled by Lock.",
    "Reload X" : "When a Unit with a Reloaded ability is played adjacent to this Unit, trigger that ability X times",
    "Reloaded" : "Trigger this ability when the Unit is played adjacent to Units with the Reload Ability",
    "Retaliation" : "Trigger this ability whenever this Unit is Damaged, but not Destroyed.",
    "Reset" : "Reset the Unit to its base Power",
    "Resilient" : "A Resilient Unit remains on the Board at the end of the Round (for 1 round only)",
    "Resistant" : "A Resistant Unit is immune to the specified Weather effect",
    "Resurrect" : "Play a card from the Graveyard",
    "Reveal" : "Turn a card or cards in the Hand over, exposing them to both players",
    "Revealed" : "A Revealed card has been turned over, exposing it to both players",
    "Revenge" : "for Deathwishes that only trigger during your opponent’s turn.",
    "Round End" : "Trigger this ability when the Round ends",
    "Shield" : "Protects a Unit from the next Power-reducing effect (Damage, Weakening or Set to Lower Power)",
    "Spawn" : "Add the card to the game and play it",
    "Spring" : "Reveal a face down Ambush card and trigger its ability",
    "Spying" : "A Unit is Spying when it is on the opposite side of the Board from the player who played it",
    "Strenghthen" : "Increase a Unit’s base Power",
    "Stubborn" : "this card cannot return to the Hand",
    "Summon" : "Play the specified cards from your Deck",
    "Swap" : "Move a card from the hand to the deck and draw another in its place",
    "Timer" : "Reduce the Timer by 1 every turn while this Unit is on the Board. Trigger the ability when it reaches 0 (at Turn Start or Turn End). Reset the Tmer when the Unit leaves the Board",
    "Transform" : "Convert into a different card",
    "Trio" : "Trigger this ability when 3 Unlocked copies of this Unit are present on the same row",
    "Truce" : "If neither player has passed",
    "Turn Start" : "This card’s ability triggers at the start of its current owner’s turn",
    "Veteran" : "Trigger this ability at the start of Rounds 2 and 3 when this card is in the Hand, Deck or Graveyard",
    "Weaken" : "Decrease a Unit’s base Power",
    "Regressing" : "The Card returns to its original Power when placed in the Graveyard",
    "Loyal" : "When you play a Unit on your side of the Board",
    "Disloyal" : "When you play a Unit on your opponent’s side"
}